- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false

- name: Fail if Docker is not installed
  ansible.builtin.fail:
    msg: "Docker is not installed. Please install Docker first."
  when: docker_check.rc != 0

- name: Install Docker Compose plugin
  ansible.builtin.command: docker plugin install --grant-all-permissions docker/compose
  register: plugin_install
  failed_when: false
  changed_when: plugin_install.rc == 0
