build_base_ansible_image:
  stage: build_base_ansible_image
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: 1
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    # Pull existing image for layer caching
    - docker pull $CI_REGISTRY_IMAGE/ansible:latest || echo "No existing image found"
    # Build with cache from existing image
    - docker build --cache-from $CI_REGISTRY_IMAGE/ansible:latest -t $CI_REGISTRY_IMAGE/ansible:latest .
    - docker push $CI_REGISTRY_IMAGE/ansible:latest
  rules:
    - changes:
        - Dockerfile
      when: always
    - when: manual
  needs: []
  cache:
    key: "docker-base-image"
    paths:
      - .docker-cache/
