# GitLab CI/CD Pipeline for Ansible Infrastructure Automation
# 
# This pipeline provides a comprehensive CI/CD workflow for Ansible-based infrastructure
# management, including Docker image building, testing, and deployment automation.
#
# WORKFLOW OVERVIEW:
# 1. Build Stage: Create Docker images for Ansible runners and testing
# 2. Test Stage: Validate Ansible code quality and syntax
#
# INCLUDED COMPONENTS:
# - Common Templates: Shared anchors and templates for common functionality
# - Image Building Jobs: Docker image creation for CI/CD runners and testing
# - Test Jobs: Ansible syntax validation and playbook testing
#
# DEPENDENCIES:
# - GitLab Registry credentials for image building
# - Ansible configuration files in ansible/ directory
#
include:
  # Common Templates
  # Reusable shell anchors and templates for common functionality
  - local: '/common.gitlab-ci.yml'

  # Local Jobs
  - local: '/ansible/images_jobs/jobs.yml'
  - local: '/ansible/test_jobs/jobs.yml'

stages:
  - build     # Build Docker images (independent)
  - test      # Test Ansible code (independent)