# GitLab CI/CD Pipeline for Ansible Infrastructure Automation
# 
# This pipeline provides a comprehensive CI/CD workflow for Ansible-based infrastructure
# management, including Docker image building and deployment automation.
#
# WORKFLOW OVERVIEW:
# 1. Build Docker Images: Create Ansible runner image
#
# INCLUDED COMPONENTS:
# - Image Building Jobs: Docker image creation for CI/CD runners
#
# 
# 
# Include external job definitions
include:
  # Common Templates
  # Reusable shell anchors and templates for common functionality
  - local: '/common.gitlab-ci.yml'
  
  # Docker Image Building Jobs
  # These jobs build the base Ansible runner image used by all other jobs
  - local: '/ansible/images_jobs/jobs.yml'

stages:
  - build     # Build Docker images (independent)