.common_before_script: &common_before_script
  - mkdir -p ~/.ansible ~/.ssh
  - chmod 700 ~/.ssh
  - ansible-playbook -i ansible/inventory.ini ansible/playbooks/setup_ci_env.yml

.test_common_before_script: &test_common_before_script
  - cd ansible/roles/$MOLECULE_ROLE_NAME
  - mkdir -p molecule/default
  - cp ../../templates/molecule.yml.j2 molecule/default/molecule.yml
  - sed "s/\${MOLECULE_ROLE_NAME}/$MOLECULE_ROLE_NAME/g" ../../templates/converge.yml.j2 > molecule/default/converge.yml
  - test -f molecule/default/prepare.yml || echo "Using default prepare.yml"
  - test -f molecule/default/verify.yml || echo "Using default verify.yml"

.test_common_after_script: &test_common_after_script
  - |
    # Clean up molecule environments safely
    cd ansible/roles/$MOLECULE_ROLE_NAME
    if [ -f molecule/default/molecule.yml ]; then
      molecule destroy --all || echo "Molecule destroy failed, but continuing..."
    fi

.generate_inventory: &generate_inventory
  - ansible-playbook ansible/playbooks/generate_inventory.yml

.generate_initial_ssh_setup_inventory: &generate_initial_ssh_setup_inventory
  - ansible-playbook ansible/playbooks/generate_initial_inventory.yml

.execute_playbook: &execute_playbook
  - |
    if [ "$CI_JOB_MANUAL" = "true" ]; then
      echo "Running pre-flight check..."
      ansible-playbook --check --diff -i ansible/inventory.ini $playbook_path
      if [ $? -ne 0 ]; then
        echo "Pre-flight check detected changes. Please review the changes above."
        exit 1
      fi
    fi
  - |
    echo "Executing playbook..."
    ansible-playbook --diff -i ansible/inventory.ini $playbook_path --retry-files-enabled



