- name: Create SSL directory
  ansible.builtin.file:
    path: "{{ app_dir }}/ssl"
    state: directory
    mode: '0755'

- name: Create chained certificate
  ansible.builtin.copy:
    content: "{{ lookup('env', 'CERTIFICATE_CRT') }}\n{{ lookup('env', 'CERTIFICATE_CA_CRT') }}"
    dest: "{{ app_dir }}/ssl/skiesdotabot.ru.chained.crt"
    mode: '0644'

- name: Copy SSL private key
  ansible.builtin.copy:
    content: "{{ lookup('env', 'CERTIFICATE_KEY') }}"
    dest: "{{ app_dir }}/ssl/certificate.key"
    mode: '0600' 
