- name: Upload private key to GitLab
  ansible.builtin.uri:
    url: "https://gitlab.com/api/v4/projects/{{ lookup('env', 'CI_PROJECT_ID') }}/variables"
    method: "{{ 'PUT' if key_result.changed else 'POST' }}"
    headers:
      PRIVATE-TOKEN: "{{ lookup('env', 'GITLAB_API_TOKEN') }}"
    body_format: json
    body:
      key: SSH_PRIVATE_KEY
      value: "{{ lookup('file', '~/.ssh/ci_id_ed25519') }}"
      protected: true
      masked: true
  delegate_to: localhost
  no_log: true 