---
galaxy_info:
  author: SkiesDota
  description: UFW firewall configuration role
  company: SkiesDota
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - firewall
    - security
    - ufw
    - networking
