- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'

- name: Generate SSH key pair
  community.crypto.openssh_keypair:
    path: "~/.ssh/ci_id_ed25519"
    type: ed25519
    state: present
  register: key_result
  delegate_to: localhost
  when: lookup('env', 'CI_JOB_NAME') == 'add_ssh_key'

- name: Upload public key to remote host
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '~/.ssh/ci_id_ed25519.pub') }}"
    state: present
    exclusive: true
  when: lookup('env', 'CI_JOB_NAME') == 'add_ssh_key' 
