---
# Main tasks file for SSH role
# This file is required for Ansible to recognize this as a valid role
# Individual task files are called using tasks_from parameter in playbooks

- name: Include default SSH setup
  ansible.builtin.include_tasks: setup_agent.yml
