name: Run Ansible Playbook
description: Runs Ansible with inventory generation and specified playbook using SSH key authentication.

inputs:
  ansible_hosts:
    description: 'Line-separated list of Ansible host IPs'
    required: true
  ansible_user:
    description: 'Ansible SSH username'
    required: false
    default: 'root'
  ssh_private_key:
    description: 'SSH private key for authentication'
    required: true
  playbook:
    description: 'Path to the Ansible playbook to run (relative to ansible/ directory)'
    required: true
  use_template_playbook:
    description: 'If true, use playbook from templates repo instead of calling repo'
    required: false
    default: 'false'
  ansible_extra_env_json:
    description: 'Additional environment variables as JSON object (non-sensitive)'
    required: false
    default: '{}'
  ansible_extra_secrets_json:
    description: 'Additional secrets as JSON object (sensitive)'
    required: false
    default: '{}'

runs:
  using: composite
  steps:
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Dynamically Scan and Add Known Hosts
      run: |
        mkdir -p ~/.ssh
        # Read newline-separated hosts
        while IFS= read -r host; do
          # Skip empty lines
          if [ -n "$host" ]; then
            SCAN=$(ssh-keyscan -H "$host" 2>/dev/null)
            if [ -n "$SCAN" ]; then
              echo "$SCAN" >> ~/.ssh/known_hosts
              echo "Added $host to known_hosts"
            else
              echo "Warning: Failed to scan $host"
            fi
          fi
        done <<< "${{ inputs.ansible_hosts }}"
      shell: bash

    - name: Run Ansible Playbooks in Docker
      run: |
        # Helper function to escape control characters in JSON strings
        # This fixes common issues like unescaped newlines in private keys
        escape_json_string() {
          local json_str="$1"
          # Try to parse as-is first
          if echo "$json_str" | jq empty 2>/dev/null; then
            echo "$json_str"
            return 0
          fi
          
          # If parsing fails, use the helper script to fix control characters
          echo "$json_str" | python3 "$GITHUB_ACTION_PATH/escape_json.py"
        }
        
        # Validate and merge extra env vars and secrets JSONs
        # First, validate each JSON input separately to provide clear error messages
        ENV_JSON_RAW='${{ inputs.ansible_extra_env_json }}'
        SECRETS_JSON_RAW='${{ inputs.ansible_extra_secrets_json }}'
        
        # Escape control characters if needed
        ENV_JSON=$(echo "$ENV_JSON_RAW" | escape_json_string)
        SECRETS_JSON=$(echo "$SECRETS_JSON_RAW" | escape_json_string)
        
        # Validate ansible_extra_env_json
        if ! echo "$ENV_JSON" | jq empty 2>/dev/null; then
          echo "Error: ansible_extra_env_json contains invalid JSON after auto-escaping"
          echo "Please ensure your JSON is valid. Control characters should be escaped."
          exit 1
        fi
        
        # Validate ansible_extra_secrets_json
        if ! echo "$SECRETS_JSON" | jq empty 2>/dev/null; then
          echo "Error: ansible_extra_secrets_json contains invalid JSON after auto-escaping"
          echo "Please ensure your JSON is valid. Control characters should be escaped."
          exit 1
        fi
        
        # Merge the validated JSONs
        MERGED_JSON=$(jq -s '.[0] * .[1]' <(echo "$ENV_JSON") <(echo "$SECRETS_JSON"))
        
        # Parse merged JSON to Docker env flags
        EXTRA_ENV_FLAGS=""
        if [ "$MERGED_JSON" != "{}" ] && [ -n "$MERGED_JSON" ]; then
          echo "Parsing extra environment variables and secrets..."
          EXTRA_ENV_FLAGS=$(echo "$MERGED_JSON" | jq -r 'to_entries[] | "-e \(.key)=\(.value | @sh)"' | tr '\n' ' ')
          echo "Extra environment flags configured (count: $(echo "$MERGED_JSON" | jq 'length'))"
        fi
        
        # Determine playbook path based on use_template_playbook flag
        if [ "${{ inputs.use_template_playbook }}" = "true" ]; then
          PLAYBOOK_PATH="templates/ansible/${{ inputs.playbook }}"
        else
          PLAYBOOK_PATH="ansible/${{ inputs.playbook }}"
        fi
        
        # Run Ansible with all environment variables
        docker run --rm \
          -v $GITHUB_WORKSPACE:/workspace \
          -v $SSH_AUTH_SOCK:/ssh-agent \
          -v ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro \
          -e SSH_AUTH_SOCK=/ssh-agent \
          -e ANSIBLE_HOSTS="${{ inputs.ansible_hosts }}" \
          -e ANSIBLE_USER="${{ inputs.ansible_user }}" \
          $EXTRA_ENV_FLAGS \
          -w /workspace \
          ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod:latest \
          bash -c "ansible-playbook templates/ansible/playbooks/generate_inventory.yml && ansible-playbook -i ansible/inventory.ini $PLAYBOOK_PATH"
      shell: bash
