name: Run Ansible Playbook
description: Runs Ansible with inventory generation and specified playbook using SSH key authentication.

inputs:
  ansible_hosts:
    description: 'Line-separated list of Ansible host IPs'
    required: true
  ansible_user:
    description: 'Ansible SSH username'
    required: false
    default: 'root'
  ssh_private_key:
    description: 'SSH private key for authentication'
    required: true
  playbook:
    description: 'Path to the Ansible playbook to run (relative to ansible/ directory)'
    required: true
  use_template_playbook:
    description: 'If true, use playbook from templates repo instead of calling repo'
    required: false
    default: 'false'
  ansible_extra_env_json:
    description: 'Additional environment variables as JSON object (non-sensitive)'
    required: false
    default: '{}'
  ansible_extra_secrets_json:
    description: 'Additional secrets as JSON object (sensitive)'
    required: false
    default: '{}'
  disable_host_key_checking:
    description: 'If true, disables SSH host key checking (useful for same-cluster runners)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Dynamically Scan and Add Known Hosts
      run: |
        mkdir -p ~/.ssh
        # Read newline-separated hosts
        while IFS= read -r host; do
          # Skip empty lines
          if [ -n "$host" ]; then
            SCAN=$(ssh-keyscan -H "$host" 2>/dev/null)
            if [ -n "$SCAN" ]; then
              echo "$SCAN" >> ~/.ssh/known_hosts
              echo "Added $host to known_hosts"
            else
              echo "Warning: Failed to scan $host"
            fi
          fi
        done <<< "${{ inputs.ansible_hosts }}"
      shell: bash

    - name: Run Ansible Playbooks in Docker
      run: |
        # Base64 encode raw JSON inputs to safely handle multiline strings and special characters
        # Then decode, fix literal newlines in string values, and parse as JSON
        ENV_JSON_RAW='${{ inputs.ansible_extra_env_json }}'
        SECRETS_JSON_RAW='${{ inputs.ansible_extra_secrets_json }}'
        
        if [ -z "$ENV_JSON_RAW" ] || [ "$ENV_JSON_RAW" = "{}" ]; then
          ENV_JSON="{}"
        else
          # Encode to base64, decode, then use Python to properly escape newlines in JSON string values
          ENV_JSON_DECODED=$(printf '%s' "$ENV_JSON_RAW" | base64 | tr -d '\n' | base64 -d)
          ENV_JSON_FIXED=$(python3 -c "import sys, re; json_str = sys.stdin.read(); fixed = re.sub(r'(?<!\\)\n(?=[^\"])', r'\\\\n', json_str); print(fixed)" <<< "$ENV_JSON_DECODED")
          if ! ENV_JSON=$(echo "$ENV_JSON_FIXED" | jq . 2>/dev/null); then
            echo "Error: Invalid JSON in ansible_extra_env_json"
            exit 1
          fi
        fi
        
        if [ -z "$SECRETS_JSON_RAW" ] || [ "$SECRETS_JSON_RAW" = "{}" ]; then
          SECRETS_JSON="{}"
        else
          # Encode to base64, decode, then use Python to properly escape newlines in JSON string values
          SECRETS_JSON_DECODED=$(printf '%s' "$SECRETS_JSON_RAW" | base64 | tr -d '\n' | base64 -d)
          SECRETS_JSON_FIXED=$(python3 -c "import sys, re; json_str = sys.stdin.read(); fixed = re.sub(r'(?<!\\)\n(?=[^\"])', r'\\\\n', json_str); print(fixed)" <<< "$SECRETS_JSON_DECODED")
          if ! SECRETS_JSON=$(echo "$SECRETS_JSON_FIXED" | jq . 2>/dev/null); then
            echo "Error: Invalid JSON in ansible_extra_secrets_json"
            exit 1
          fi
        fi
        
        MERGED_JSON=$(jq -s '.[0] * .[1]' <(echo "$ENV_JSON") <(echo "$SECRETS_JSON"))
        
        PLAYBOOK_PATH="$([ "${{ inputs.use_template_playbook }}" = "true" ] && echo "templates/ansible/${{ inputs.playbook }}" || echo "ansible/${{ inputs.playbook }}")"
        
        DOCKER_ARGS=(
          -v "$GITHUB_WORKSPACE:/workspace"
          -v "$SSH_AUTH_SOCK:/ssh-agent"
          -e "SSH_AUTH_SOCK=/ssh-agent"
          -e "ANSIBLE_HOSTS=${{ inputs.ansible_hosts }}"
          -e "ANSIBLE_USER=${{ inputs.ansible_user }}"
        )
        
        if [ "${{ inputs.disable_host_key_checking }}" = "true" ]; then
          DOCKER_ARGS+=(-e "ANSIBLE_HOST_KEY_CHECKING=False" -e "ANSIBLE_SSH_ARGS=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null")
        else
          DOCKER_ARGS+=(-v ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro)
        fi
        
        [ "$MERGED_JSON" != "{}" ] && while IFS= read -r line; do
          [ -n "$line" ] && DOCKER_ARGS+=(-e "$line")
        done < <(echo "$MERGED_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value | @sh)"')
        
        # Mount host network when running in same cluster (allows pod-to-node SSH)
        if [ "${{ inputs.disable_host_key_checking }}" = "true" ]; then
          DOCKER_ARGS+=(--network host)
        fi
        
        docker run --rm "${DOCKER_ARGS[@]}" -w /workspace \
          ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod:latest \
          bash -c "ansible-playbook templates/ansible/playbooks/generate_inventory.yml && ansible-playbook -i ansible/inventory.ini $PLAYBOOK_PATH"
      shell: bash
