name: Run Ansible Playbook
description: Runs Ansible with inventory generation and specified playbook using SSH key authentication.

inputs:
  ansible_hosts:
    description: 'Line-separated list of Ansible host IPs'
    required: true
  ansible_user:
    description: 'Ansible SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key for authentication'
    required: true
  playbook:
    description: 'Path to the Ansible playbook to run (relative to ansible/ directory)'
    required: true

runs:
  using: composite
  steps:
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Dynamically Scan and Add Known Hosts
      run: |
        mkdir -p ~/.ssh
        # Read newline-separated hosts
        while IFS= read -r host; do
          # Skip empty lines
          if [ -n "$host" ]; then
            SCAN=$(ssh-keyscan -H "$host" 2>/dev/null)
            if [ -n "$SCAN" ]; then
              echo "$SCAN" >> ~/.ssh/known_hosts
              echo "Added $host to known_hosts"
            else
              echo "Warning: Failed to scan $host"
            fi
          fi
        done <<< "${{ inputs.ansible_hosts }}"
      shell: bash

    - name: Run Ansible Playbooks
      run: |
        ansible-playbook $GITHUB_WORKSPACE/templates/ansible/playbooks/generate_inventory.yml
        ansible-playbook -i $GITHUB_WORKSPACE/inventory.ini ansible/${{ inputs.playbook }} --verbose
      shell: bash
      env:
        ANSIBLE_HOSTS: ${{ inputs.ansible_hosts }}
        ANSIBLE_USER: ${{ inputs.ansible_user }}
