name: Run Ansible Playbook
description: Runs Ansible with inventory generation and specified playbook using SSH key authentication.

inputs:
  ansible_hosts:
    description: 'Line-separated list of Ansible host IPs'
    required: true
  ansible_user:
    description: 'Ansible SSH username'
    required: false
    default: 'root'
  ssh_private_key:
    description: 'SSH private key for authentication'
    required: true
  playbook:
    description: 'Path to the Ansible playbook to run (relative to ansible/ directory)'
    required: true
  use_template_playbook:
    description: 'If true, use playbook from templates repo instead of calling repo'
    required: false
    default: 'false'
  ansible_extra_env_json:
    description: 'Additional environment variables as JSON object (non-sensitive)'
    required: false
    default: '{}'
  ansible_extra_secrets_json:
    description: 'Additional secrets as JSON object (sensitive)'
    required: false
    default: '{}'
  disable_host_key_checking:
    description: 'If true, disables SSH host key checking (useful for same-cluster runners)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Dynamically Scan and Add Known Hosts
      run: |
        mkdir -p ~/.ssh
        # Read newline-separated hosts
        while IFS= read -r host; do
          # Skip empty lines
          if [ -n "$host" ]; then
            SCAN=$(ssh-keyscan -H "$host" 2>/dev/null)
            if [ -n "$SCAN" ]; then
              echo "$SCAN" >> ~/.ssh/known_hosts
              echo "Added $host to known_hosts"
            else
              echo "Warning: Failed to scan $host"
            fi
          fi
        done <<< "${{ inputs.ansible_hosts }}"
      shell: bash

    - name: Run Ansible Playbooks in Docker
      run: |
        fix_json() {
          [ -z "$1" ] && echo "{}" && return
          echo "$1" | jq empty 2>/dev/null && echo "$1" || echo "$1" | python3 "$GITHUB_ACTION_PATH/escape_json.py" || echo "{}"
        }
        
        ENV_JSON=$(fix_json '${{ inputs.ansible_extra_env_json }}')
        SECRETS_JSON=$(fix_json '${{ inputs.ansible_extra_secrets_json }}')
        MERGED_JSON=$(jq -s '.[0] * .[1]' <(echo "$ENV_JSON") <(echo "$SECRETS_JSON"))
        
        PLAYBOOK_PATH="$([ "${{ inputs.use_template_playbook }}" = "true" ] && echo "templates/ansible/${{ inputs.playbook }}" || echo "ansible/${{ inputs.playbook }}")"
        
        DOCKER_ARGS=(
          -v "$GITHUB_WORKSPACE:/workspace"
          -v "$SSH_AUTH_SOCK:/ssh-agent"
          -v ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
          -e "SSH_AUTH_SOCK=/ssh-agent"
          -e "ANSIBLE_HOSTS=${{ inputs.ansible_hosts }}"
          -e "ANSIBLE_USER=${{ inputs.ansible_user }}"
        )
        
        # Conditionally disable host key checking if requested (for same-cluster runners)
        if [ "${{ inputs.disable_host_key_checking }}" = "true" ]; then
          DOCKER_ARGS+=(-e "ANSIBLE_HOST_KEY_CHECKING=False")
        fi
        
        [ "$MERGED_JSON" != "{}" ] && while IFS= read -r line; do
          [ -n "$line" ] && DOCKER_ARGS+=(-e "$line")
        done < <(echo "$MERGED_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value | @sh)"')
        
        docker run --rm "${DOCKER_ARGS[@]}" -w /workspace \
          ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod:latest \
          bash -c "ansible-playbook templates/ansible/playbooks/generate_inventory.yml && ansible-playbook -i ansible/inventory.ini $PLAYBOOK_PATH"
      shell: bash
