name: Run Ansible Playbook
description: Runs Ansible with inventory generation and specified playbook using SSH key authentication.

inputs:
  ansible_hosts:
    description: 'Line-separated list of Ansible host IPs'
    required: true
  ansible_user:
    description: 'Ansible SSH username'
    required: false
    default: 'root'
  ssh_private_key:
    description: 'SSH private key for authentication'
    required: true
  playbook:
    description: 'Path to the Ansible playbook to run (relative to ansible/ directory)'
    required: true
  use_template_playbook:
    description: 'If true, use playbook from templates repo instead of calling repo'
    required: false
    default: 'false'
  ansible_extra_env_json:
    description: 'Additional environment variables as JSON object (non-sensitive)'
    required: false
    default: '{}'
  ansible_extra_secrets_json:
    description: 'Additional secrets as JSON object (sensitive)'
    required: false
    default: '{}'
  runners_in_the_same_network:
    description: 'If true, uses host network mode and disables SSH host key checking (for pod-to-node SSH in Kubernetes)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run Ansible Playbooks in Docker
      run: |
        # Parse and validate JSON inputs
        ENV_JSON_RAW='${{ inputs.ansible_extra_env_json }}'
        SECRETS_JSON_RAW='${{ inputs.ansible_extra_secrets_json }}'
        
        if ! ENV_JSON=$(echo "$ENV_JSON_RAW" | jq . 2>/dev/null); then
          echo "Error: Invalid JSON in ansible_extra_env_json" >&2
          exit 1
        fi
        
        if ! SECRETS_JSON=$(echo "$SECRETS_JSON_RAW" | jq . 2>/dev/null); then
          echo "Error: Invalid JSON in ansible_extra_secrets_json" >&2
          exit 1
        fi
        
        MERGED_JSON=$(jq -s '.[0] * .[1]' <(echo "$ENV_JSON") <(echo "$SECRETS_JSON"))
        PLAYBOOK_PATH="$([ "${{ inputs.use_template_playbook }}" = "true" ] && echo "templates/ansible/${{ inputs.playbook }}" || echo "ansible/${{ inputs.playbook }}")"
        
        # Build Docker arguments
        DOCKER_ARGS=(
          -v "$GITHUB_WORKSPACE:/workspace"
          -e "ANSIBLE_HOSTS=${{ inputs.ansible_hosts }}"
          -e "ANSIBLE_USER=${{ inputs.ansible_user }}"
          -e "ANSIBLE_SSH_PRIVATE_KEY_FILE=/root/.ssh/id_rsa"
          -e "SSH_PRIVATE_KEY=${{ inputs.ssh_private_key }}"
          -e "ANSIBLE_SSH_ARGS=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        )
        
        
        
        # Add merged environment variables
        [ "$MERGED_JSON" != "{}" ] && while IFS= read -r line; do
          [ -n "$line" ] && DOCKER_ARGS+=(-e "$line")
        done < <(echo "$MERGED_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"')
        
        docker run --rm "${DOCKER_ARGS[@]}" -w /workspace \
          ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod:latest \
          bash -c "
            # Write SSH key from environment variable to file
            mkdir -p ~/.ssh
            echo \"\$SSH_PRIVATE_KEY\" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            
            if [ ! -s ~/.ssh/id_rsa ]; then
              echo 'Error: Failed to create SSH key file' >&2
              exit 1
            fi
            
            ansible-playbook templates/ansible/playbooks/generate_inventory.yml
            ansible-playbook -i ansible/inventory.ini $PLAYBOOK_PATH
          "
      shell: bash
