- name: Start SSH agent
  ansible.builtin.command: ssh-agent -s
  register: ssh_agent_output
  changed_when: false

- name: Extract SSH agent PID
  ansible.builtin.set_fact:
    ssh_agent_pid: "{{ ssh_agent_output.stdout | regex_search('SSH_AGENT_PID=(\\d+)', '\\1') | default('') }}"

- name: Extract SSH auth socket
  ansible.builtin.set_fact:
    ssh_auth_sock: "{{ ssh_agent_output.stdout | regex_search('SSH_AUTH_SOCK=([^;\\s]+)', '\\1') | default('') }}"

- name: Add SSH key to agent
  ansible.builtin.command: "ssh-add -"
  args:
    stdin: "{{ lookup('env', 'SSH_PRIVATE_KEY', default='') | regex_replace('\r', '') }}"
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock }}"
    SSH_AGENT_PID: "{{ ssh_agent_pid }}"
  changed_when: false
  when: ssh_agent_pid != '' and ssh_auth_sock != '' and lookup('env', 'SSH_PRIVATE_KEY', default='') != ''

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: "0700"

- name: Add known hosts
  ansible.posix.known_hosts:
    host: "{{ item }}"
    state: present
  loop: "{{ lookup('env', 'ANSIBLE_HOSTS', default='').split('\n') | select('string') | list }}"
  when: lookup('env', 'ANSIBLE_HOSTS', default='') != ''
