---
- name: Prepare MongoDB Environment (Optimized)
  hosts: all
  become: true
  tasks:
    - name: Start MongoDB container with optimized settings
      ansible.builtin.docker_container:
        name: mongodb
        image: mongo:7.0
        state: started
        ports:
          - "27017:27017"
        command: mongod --replSet rs0 --bind_ip_all --wiredTigerCacheSizeGB 0.5
        restart_policy: unless-stopped
        wait: true
        wait_timeout: 30
        env:
          MONGO_INITDB_DATABASE: test
        ulimits:
          - "nofile:64000:64000"

    - name: Wait for MongoDB to be ready (optimized)
      ansible.builtin.wait_for:
        port: 27017
        timeout: 30
        delay: 5

    - name: Pre-initialize replica set configuration
      ansible.builtin.set_fact:
        mongo_hosts:
          - "{{ ansible_default_ipv4.address }}:27017"
          - "{{ ansible_default_ipv4.address }}:27018"
          - "{{ ansible_default_ipv4.address }}:27019" 