---
- name: Prepare MongoDB Environment
  hosts: all
  tasks:
    - name: Wait for MongoDB to be ready
      ansible.builtin.wait_for:
        port: 27017
        timeout: 30

    - name: Test MongoDB connection
      ansible.builtin.command: mongosh --eval "db.runCommand('ping')"
      register: mongo_test
      retries: 5
      delay: 5
      until: mongo_test.rc == 0

    - name: Set replica set configuration
      ansible.builtin.set_fact:
        mongo_hosts:
          - "{{ ansible_default_ipv4.address }}:27017"
          - "{{ ansible_default_ipv4.address }}:27018"
          - "{{ ansible_default_ipv4.address }}:27019" 