---
- name: Prepare MongoDB Environment
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Ensure Docker is running and accessible
      ansible.builtin.command: docker ps
      register: docker_check
      failed_when: false
      changed_when: false

    - name: Fail if Docker is not available
      ansible.builtin.fail:
        msg: "Docker is not available or not running. Check Docker socket permissions."
      when: docker_check.rc != 0

    - name: Create necessary directories for MongoDB
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /tmp/mongodb_data
        - /tmp/mongodb_logs

    - name: Remove existing MongoDB container if exists
      ansible.builtin.docker_container:
        name: mongodb
        state: absent
      ignore_errors: true

    - name: Start MongoDB container (simple configuration)
      ansible.builtin.docker_container:
        name: mongodb
        image: mongo:6.0
        state: started
        ports:
          - "27017:27017"
        command: mongod --bind_ip_all
        restart_policy: unless-stopped
        env:
          MONGO_INITDB_DATABASE: test

    - name: Wait for MongoDB to be ready
      ansible.builtin.wait_for:
        port: 27017
        timeout: 30
        delay: 5

    - name: Test MongoDB connection
      ansible.builtin.command: docker exec mongodb mongosh --eval "db.runCommand('ping')"
      register: mongo_test
      changed_when: false
      retries: 3
      delay: 5
      until: mongo_test.rc == 0

    - name: Set replica set configuration with fake ephemeral IPs
      ansible.builtin.set_fact:
        mongo_hosts:
          - "10.0.0.1:27017"
          - "10.0.0.2:27018"
          - "10.0.0.3:27019" 