---
- name: Verify MongoDB Configuration
  hosts: instance
  connection: local
  tasks:
    - name: Check if MongoDB container is running
      ansible.builtin.command: docker ps --filter name=mongodb --format "{{.Names}}"
      register: mongodb_container
      changed_when: false

    - name: Fail if MongoDB container is not running
      ansible.builtin.fail:
        msg: "MongoDB container is not running"
      when: "'mongodb' not in mongodb_container.stdout"

    - name: Check replica set status
      ansible.builtin.command: docker exec mongodb mongosh --eval "rs.status().ok"
      register: rs_status
      changed_when: false

    - name: Verify replica set is initialized
      ansible.builtin.assert:
        that:
          - rs_status.stdout | trim == "1"
        fail_msg: "Replica set is not properly initialized"

    - name: Check replica set configuration
      ansible.builtin.command: docker exec mongodb mongosh --eval "rs.conf()._id"
      register: rs_config
      changed_when: false

    - name: Verify replica set ID
      ansible.builtin.assert:
        that:
          - rs_config.stdout | trim == "rs0"
        fail_msg: "Replica set ID is not correctly configured"

    - name: Check if indexes were created (verify role execution)
      ansible.builtin.command: docker exec mongodb mongosh --eval "db.active_actions.getIndexes().length"
      register: active_actions_count
      changed_when: false

    - name: Verify active_actions indexes exist (role responsibility)
      ansible.builtin.assert:
        that:
          - active_actions_count.stdout | trim | int >= 3
        fail_msg: "active_actions collection does not have the expected number of indexes"

    - name: Check completed_operations indexes count
      ansible.builtin.command: docker exec mongodb mongosh --eval "db.completed_operations.getIndexes().length"
      register: completed_operations_count
      changed_when: false

    - name: Verify completed_operations indexes exist (role responsibility)
      ansible.builtin.assert:
        that:
          - completed_operations_count.stdout | trim | int >= 2
        fail_msg: "completed_operations collection does not have the expected number of indexes"

    - name: Check cache_version indexes count
      ansible.builtin.command: docker exec mongodb mongosh --eval "db.cache_version.getIndexes().length"
      register: cache_version_count
      changed_when: false

    - name: Verify cache_version indexes exist (role responsibility)
      ansible.builtin.assert:
        that:
          - cache_version_count.stdout | trim | int >= 1
        fail_msg: "cache_version collection does not have the expected number of indexes"

    - name: Verify TTL index exists (role responsibility)
      ansible.builtin.command: docker exec mongodb mongosh --eval "db.completed_operations.getIndexes().forEach(function(idx) { if(idx.expireAfterSeconds) print('TTL_EXISTS'); })"
      register: ttl_check
      changed_when: false

    - name: Verify TTL index was created
      ansible.builtin.assert:
        that:
          - "'TTL_EXISTS' in ttl_check.stdout"
        fail_msg: "TTL index on completed_operations was not created by the role" 