.base_molecule:
  stage: test
  image: $CI_REGISTRY_IMAGE/ansible-test:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - !reference [.test_common_before_script]
  script:
    - molecule test
  after_script:
    - |
      # Clean up molecule environments safely
      cd ansible/roles/$MOLECULE_ROLE_NAME
      if [ -f molecule/default/molecule.yml ]; then
        molecule destroy --all || echo "Molecule destroy failed, but continuing..."
      fi
  rules:
    - changes:
        - ansible/roles/${MOLECULE_ROLE_NAME}/**/*
      when: always
    - when: manual
  needs: []

test_mongodb:
  extends: .base_molecule
  variables:
    MOLECULE_ROLE_NAME: mongodb
