.base_test_role_playbook: 
  stage: test
  image: $CI_REGISTRY_IMAGE/ansible-test:latest

test_ansible_syntax:
  extends: .base_test_role_playbook
  script:
    - |
      for role in ansible/roles/*/; do
        echo "CHECKING ROLE: $role"
        python -m ansiblelint "$role" --nocolor
      done
    - |
      for playbook in ansible/playbooks/*.yml; do
  rules:
    - changes:
        - Dockerfile.test
      when: always
      needs:
        - build_test_ansible_image
    - changes:
        - ansible/playbooks/**/*
        - ansible/roles/**/*
      when: always
      needs: []
    - when: manual
      needs: []

test_playbooks:
  extends: .base_test_role_playbook
  script:
    - |
      for playbook in ansible/playbooks/*.yml; do
        echo "CHECKING PLAYBOOK: $playbook"
        python -m ansible-playbook "$playbook" --check --diff -i localhost
      done
  rules:
    - changes:
        - ansible/playbooks/**/*
        - ansible/roles/**/*
      when: always
      needs:
        - test_ansible_syntax
    - when: manual
      needs: []