.base_test_ansible:
  stage: test
  image: python:3.13-slim

.script_test_ansible_syntax:
  script: &script_test_ansible_syntax
    - |
      for role in ansible/roles/*/; do
        echo "CHECKING ROLE: $role"
        python -m ansiblelint "$role" --nocolor
      done
    - |
      for playbook in ansible/playbooks/*.yml; do
        echo "CHECKING PLAYBOOK: $playbook"
        python -m ansiblelint "$playbook" --nocolor
      done

.script_test_playbooks:
  script: &script_test_playbooks
    - |
      for playbook in ansible/playbooks/*.yml; do
        echo "CHECKING PLAYBOOK: $playbook"
        python -m ansible-playbook "$playbook" --check --diff -i localhost
      done

test_ansible_syntax_manual:
  extends: .base_test_ansible
  before_script:
    - pip install ansible-lint
  script: *script_test_ansible_syntax
  rules:
    - when: manual
      needs: []

test_playbooks_manual:
  extends: .base_test_ansible
  before_script:
    - pip install ansible
  script: *script_test_playbooks
  rules:
    - when: manual  
      needs: []

test_ansible_syntax_auto:
  extends: .base_test_ansible
  before_script:
    - pip install ansible-lint
  script: *script_test_ansible_syntax
  rules:
    - changes:
        - ansible/playbooks/**/*
        - ansible/roles/**/*
      when: always
      needs: []

test_playbooks_auto:
  extends: .base_test_ansible
  before_script:
    - pip install ansible
  script: *script_test_playbooks
  rules:
    - changes:
        - ansible/playbooks/**/*
        - ansible/roles/**/*
      when: always
      needs:
        - test_ansible_syntax_auto
