.base_test_role_playbook: 
  stage: test
  image: $CI_REGISTRY_IMAGE/ansible-test:latest

.script_test_ansible_syntax:
  script:
    - |
      for role in ansible/roles/*/; do
        echo "CHECKING ROLE: $role"
        python -m ansible-lint "$role" --nocolor
      done
    - |
      for playbook in ansible/playbooks/*.yml; do
        echo "CHECKING PLAYBOOK: $playbook"
        python -m ansiblelint "$playbook" --nocolor
      done

.script_test_playbooks:
  script:
    - |
      for playbook in ansible/playbooks/*.yml; do
        echo "CHECKING PLAYBOOK: $playbook"
        python -m ansible-playbook "$playbook" --check --diff -i localhost
      done

test_ansible_syntax_manual:
  extends: .base_test_role_playbook
  script: .script_test_ansible_syntax
  rules:
    - when: manual
      allow_failure: true

test_playbooks_manual:
  extends: .base_test_role_playbook
  script: .script_test_playbooks
  rules:
    - when: manual
      allow_failure: true

test_ansible_syntax:
  extends: .base_test_role_playbook
  script: .script_test_ansible_syntax
  rules:
    - changes:
        - Dockerfile.test
      when: always
      needs:
        - build_test_ansible_image
    - changes:
        - ansible/playbooks/**/*
        - ansible/roles/**/*
      when: always
      needs: []

test_playbooks:
  extends: .base_test_role_playbook
  script: .script_test_playbooks
  rules:
    - changes:
        - ansible/playbooks/**/*
        - ansible/roles/**/*
      when: always
      needs:
        - test_ansible_syntax
