.base_molecule:
  stage: test
  image: $CI_REGISTRY_IMAGE/ansible-test:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - !reference [.test_common_before_script]
  script:
    - molecule test
  after_script:
    - !reference [.test_common_after_script]
  rules:
    - changes:
        - Dockerfile.test
      when: always
      needs:
        - build_test_image
    - changes:
        - ansible/roles/${MOLECULE_ROLE_NAME}/**/*
      when: always
      needs: []
    - when: manual
      needs: []


test_mongodb:
  extends: .base_molecule
  variables:
    MOLECULE_ROLE_NAME: mongodb