---
galaxy_info:
  author: SkiesDota
  description: Docker Compose plugin management role
  company: SkiesDota
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: CentOS
      versions:
        - all
  galaxy_tags:
    - docker
    - docker-compose
    - containerization
    - orchestration

dependencies:
  - role: docker 