---
- name: Setup CI/CD Environment
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Setup SSH environment
      ansible.builtin.import_role:
        name: ssh
        tasks_from: setup_agent

    - name: Add provided known hosts
      ansible.builtin.copy:
        content: "{{ lookup('env', 'SSH_KNOWN_HOSTS') }}"
        dest: "~/.ssh/known_hosts"
        mode: "0644"
      when: lookup('env', 'SSH_KNOWN_HOSTS') != ''
