---
- name: Setup CI/CD Environment
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Setup SSH environment
      ansible.builtin.import_role:
        name: ssh
        tasks_from: setup_agent