.common_before_script: &common_before_script
  - name: Setup SSH environment
    ansible.builtin.import_role:
      name: ssh
      tasks_from: setup_agent

  - name: Configure Ansible
    ansible.builtin.template:
      src: ansible.cfg.j2
      dest: ~/.ansible/ansible.cfg
      mode: '0644'

.test_common_before_script: &test_common_before_script
  - name: Change to role directory
    ansible.builtin.shell:
      cmd: cd ansible/roles/{{ MOLECULE_ROLE_NAME }}
    changed_when: false

  - name: Create molecule directory structure
    ansible.builtin.file:
      path: molecule/default
      state: directory
      mode: '0755'

  - name: Copy molecule.yml template with environment substitution
    ansible.builtin.template:
      src: ../../templates/molecule.yml.j2
      dest: molecule/default/molecule.yml
      mode: '0644'

  - name: Copy converge.yml template with environment substitution
    ansible.builtin.template:
      src: ../../templates/converge.yml.j2
      dest: molecule/default/converge.yml
      mode: '0644'

  - name: Create requirements.yml if it doesn't exist
    ansible.builtin.file:
      path: requirements.yml
      state: touch
      mode: '0644'

.generate_inventory: &generate_inventory
  - name: Generate inventory file
    ansible.builtin.template:
      src: inventory.j2
      dest: ansible/inventory.ini
      mode: '0644'

.generate_initial_ssh_setup_inventory: &generate_initial_ssh_setup_inventory
  - name: Generate initial ssh setup inventory file
    ansible.builtin.template:
      src: initial_ssh_setup_inventory.j2
      dest: ansible/inventory.ini
      mode: '0644'

.execute_playbook: &execute_playbook
  - name: Pre-flight check
    ansible.builtin.command:
      cmd: "ansible-playbook --check --diff -i ansible/inventory.ini {{ playbook_path }} {% if check_tags is defined %}--tags {{ check_tags }}{% endif %}"
    register: check_result
    failed_when: false
    changed_when: false
    when: manual_job | default(false)

  - name: Display check results
    ansible.builtin.debug:
      msg: "{{ check_result.stdout_lines }}"
    when: manual_job | default(false) and check_result.rc == 0

  - name: Fail if check shows changes
    ansible.builtin.fail:
      msg: "Pre-flight check detected changes. Please review the changes above."
    when: manual_job | default(false) and check_result.rc != 0

  - name: Execute playbook
    ansible.builtin.command:
      cmd: "ansible-playbook --diff -i ansible/inventory.ini {{ playbook_path }} --retry-files-enabled {% if check_tags is defined %}--tags {{ check_tags }}{% endif %}"
    register: playbook_result
    when: not manual_job | default(false) or check_result.rc == 0

  - name: Display execution results
    ansible.builtin.debug:
      msg: "{{ playbook_result.stdout_lines }}"
    when: playbook_result is defined



