- name: Check if replica set is already initialized
  ansible.builtin.docker_container:
    name: mongodb
    command: mongosh --eval "rs.status()"
  register: rs_status
  changed_when: false
  failed_when: false

- name: Initialize MongoDB replica set
  ansible.builtin.docker_container:
    name: mongodb 
    command: mongosh --eval "{{ lookup('template', 'init_replica_set.js') | replace('\n', ' ') }}"
  when: "'PRIMARY' not in rs_status.stdout"

- name: Wait for replica set initialization
  ansible.builtin.wait_for:
    port: 27017
    timeout: 60
  when: "'PRIMARY' not in rs_status.stdout"