- name: Check if indexes exist
  ansible.builtin.docker_container:
    name: mongodb
    command: mongosh --eval "db.active_actions.getIndexes().length > 1"
  register: indexes_status
  changed_when: false
  failed_when: false
  delegate_to: localhost

- name: Wait for MongoDB to be ready before index creation
  ansible.builtin.wait_for:
    port: 27017
    timeout: 30
    delay: 5
  delegate_to: localhost

- name: Create MongoDB indexes
  ansible.builtin.docker_container:
    name: mongodb
    command: mongosh --eval "{{ lookup('file', 'setup_indexes.js') | replace('\n', ' ') }}"
  when: indexes_status.stdout | trim | lower != "true"
  delegate_to: localhost