- name: Check if indexes exist
  ansible.builtin.command: mongosh --eval "db.active_actions.getIndexes().length > 1"
  register: indexes_status
  changed_when: false
  failed_when: false

- name: Create MongoDB indexes
  ansible.builtin.command: mongosh --eval "{{ lookup('file', 'setup_indexes.js') | replace('\n', ' ') }}"
  when: indexes_status.stdout | trim | lower != "true"