---
galaxy_info:
  author: SkiesDota
  description: SSL certificate management role
  company: SkiesDota
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - ssl
    - certificates
    - security
    - tls
