name: 'Setup Docker'
description: 'Setup Docker Buildx and login to GitHub Container Registry'

inputs:
  github-token:
    description: 'GitHub token for registry access'
    required: true
  registry:
    description: 'Container registry to login to'
    required: false
    default: 'ghcr.io'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: inputs.github-token != ''
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }} 