- name: Download Docker install script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: "0755"

- name: Install Docker using official script
  ansible.builtin.command: /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
