[all]
62.84.183.143 ansible_user=root ansible_python_interpreter=/usr/bin/python3
62.84.183.150 ansible_user=root ansible_python_interpreter=/usr/bin/python3
62.84.183.142 ansible_user=root ansible_python_interpreter=/usr/bin/python3

