collections:
  - name: community.crypto
    version: ">=1.0.0"
  - name: community.docker
    version: ">=1.0.0"
  - name: community.general
    version: ">=1.0.0"
  - name: ansible.posix
    version: ">=1.0.0"

roles:
  - name: geerlingguy.docker
    version: ">=1.0.0"
  - name: geerlingguy.firewall
    version: ">=1.0.0"