name: Auto OpenCommit Improvements

on:
  push:
    # Remove branches-ignore if you want OpenCommit to run on all branches
    # branches-ignore: [main master dev development release]

permissions:
  contents: write
  pull-requests: write

jobs:
  improve-commits:
    # Only run if this is not a merge commit and not from a fork
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge') && github.event.repository.fork == false
    uses: ./.github/workflows/reusable-opencommit.yml
    with:
      github-token: ${{ github.token }}
      min-commit-length: 15
      skip-if-already-good: 'true'

      oco-model: 'deepseek-chat'
      oco-ai-provider: 'deepseek'
      oco-language: 'en'
      oco-prompt-module: 'conventional-commit'
      oco-emoji: 'true'
    secrets:
      oco-api-key: ${{ secrets.OCO_API_KEY }}