name: Build Docker Images

on:
  push:
    paths:
      - 'Dockerfile'
      - 'Dockerfile.test'
  workflow_dispatch:

jobs:
  build-base-ansible:
    uses: ./.github/workflows/reusable-build-images.yml
    with:
      image-name: ansible-base
      dockerfile-path: ./Dockerfile
    secrets: inherit

  build-test-ansible:
    uses: ./.github/workflows/reusable-build-images.yml
    with:
      image-name: ansible-test
      dockerfile-path: ./Dockerfile.test
    secrets: inherit 