name: Build Docker Images (Concise)

on:
  push:
    paths:
      - 'Dockerfile'
      - 'Dockerfile.test'
      - 'Dockerfile.lint'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Detect changed Dockerfiles
        id: detect
        uses: ./.github/actions/detect-changes
        with:
          patterns: 'Dockerfile,Dockerfile.test,Dockerfile.lint'
          matrix-key: 'dockerfile'

  build:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Build ${{ matrix.dockerfile }}
        uses: ./.github/workflows/reusable-build-images.yml
        with:
          image-name: ${{ matrix.dockerfile == 'Dockerfile' && 'ansible-base' || matrix.dockerfile == 'Dockerfile.test' && 'ansible-test' || 'ansible-lint' }}
          dockerfile-path: ./${{ matrix.dockerfile }} 