name: Build Docker Images

on:
  push:
    paths:
      - 'Dockerfile'
      - 'Dockerfile.test'
      - 'Dockerfile.lint'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changed Dockerfiles
        id: detect
        run: |
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 2>/dev/null || echo "")
          
          # Check which Dockerfiles were changed
          CHANGED_DOCKERFILES="[]"
          if echo "$CHANGED_FILES" | grep -q "Dockerfile$"; then
            CHANGED_DOCKERFILES='["Dockerfile"]'
          fi
          if echo "$CHANGED_FILES" | grep -q "Dockerfile.test"; then
            if [ "$CHANGED_DOCKERFILES" = "[]" ]; then
              CHANGED_DOCKERFILES='["Dockerfile.test"]'
            else
              CHANGED_DOCKERFILES='["Dockerfile", "Dockerfile.test"]'
            fi
          fi
          if echo "$CHANGED_FILES" | grep -q "Dockerfile.lint"; then
            if [ "$CHANGED_DOCKERFILES" = "[]" ]; then
              CHANGED_DOCKERFILES='["Dockerfile.lint"]'
            elif [ "$CHANGED_DOCKERFILES" = '["Dockerfile"]' ]; then
              CHANGED_DOCKERFILES='["Dockerfile", "Dockerfile.lint"]'
            elif [ "$CHANGED_DOCKERFILES" = '["Dockerfile.test"]' ]; then
              CHANGED_DOCKERFILES='["Dockerfile.test", "Dockerfile.lint"]'
            else
              CHANGED_DOCKERFILES='["Dockerfile", "Dockerfile.test", "Dockerfile.lint"]'
            fi
          fi
          
          echo "matrix=$CHANGED_DOCKERFILES" >> $GITHUB_OUTPUT
          echo "Changed Dockerfiles: $CHANGED_DOCKERFILES"

  build-changed:
    if: github.event_name != 'workflow_dispatch' && needs.detect-changes.outputs.matrix != '[]'
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.dockerfile }}
        uses: ./.github/actions/build-image
        with:
          image-name: ${{ matrix.dockerfile == 'Dockerfile' && 'ansible-base' || matrix.dockerfile == 'Dockerfile.test' && 'ansible-test' || 'ansible-lint' }}
          dockerfile-path: ./${{ matrix.dockerfile }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-all:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile, Dockerfile.test, Dockerfile.lint]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.dockerfile }}
        uses: ./.github/actions/build-image
        with:
          image-name: ${{ matrix.dockerfile == 'Dockerfile' && 'ansible-base' || matrix.dockerfile == 'Dockerfile.test' && 'ansible-test' || 'ansible-lint' }}
          dockerfile-path: ./${{ matrix.dockerfile }}
          github-token: ${{ secrets.GITHUB_TOKEN }} 