name: Build Docker Images

on:
  push:
    paths:
      - 'Dockerfile'
      - 'Dockerfile.test'
      - 'Dockerfile.lint'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changed Dockerfiles
        id: detect
        uses: ./.github/actions/detect-changes
        with:
          patterns: 'Dockerfile,Dockerfile.test,Dockerfile.lint'
          matrix-key: 'dockerfile'

  build-push:
    if: github.event_name != 'workflow_dispatch'
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.dockerfile }}
        uses: ./.github/actions/build-image
        with:
          image-name: ${{ matrix.dockerfile == 'Dockerfile' && 'ansible-base' || matrix.dockerfile == 'Dockerfile.test' && 'ansible-test' || 'ansible-lint' }}
          dockerfile-path: ./${{ matrix.dockerfile }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile, Dockerfile.test, Dockerfile.lint]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.dockerfile }}
        uses: ./.github/actions/build-image
        with:
          image-name: ${{ matrix.dockerfile == 'Dockerfile' && 'ansible-base' || matrix.dockerfile == 'Dockerfile.test' && 'ansible-test' || 'ansible-lint' }}
          dockerfile-path: ./${{ matrix.dockerfile }}
          github-token: ${{ secrets.GITHUB_TOKEN }} 