name: Main Production Pipeline

on:
  push:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile*'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile*'
  workflow_dispatch:
    inputs:
      build:
        description: 'Build Docker images'
        required: false
        default: false
        type: boolean
      format-lint:
        description: 'Format and lint Ansible code'
        required: false
        default: true
        type: boolean
      test:
        description: 'Test Ansible code'
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  packages: write

jobs:
  detect-changes:
    if: |
      github.event_name != 'workflow_dispatch' || 
      (github.event_name == 'workflow_dispatch' && !inputs.build)
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.detect.outputs.changed_files }}
      dockerfiles_matrix: ${{ steps.detect.outputs.dockerfiles_matrix }}
      ansible_is_changed: ${{ steps.detect.outputs.ansible_is_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: detect
        run: |
          # Configuration
          DOCKERFILE_PATTERNS=("Dockerfile.prod" "Dockerfile.prod.test" "Dockerfile.prod.format-lint")
          ANSIBLE_PATTERN="ansible/"
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            CHANGED_FILES="ansible/**/* Dockerfile*"
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 2>/dev/null || echo "")
          fi

          echo Changed files: 
          echo "$CHANGED_FILES"
          
          # Detect Dockerfile changes
          DOCKERFILES_CHANGED=""
          for pattern in "${DOCKERFILE_PATTERNS[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "^${pattern}$"; then
              DOCKERFILES_CHANGED="${DOCKERFILES_CHANGED:+$DOCKERFILES_CHANGED }$pattern"
            fi
          done
          
          # Detect Ansible changes
          ANSIBLE_IS_CHANGED="false"
          if echo "$CHANGED_FILES" | grep -q "$ANSIBLE_PATTERN"; then
            ANSIBLE_IS_CHANGED="true"
          fi
          
          # Build matrix for Docker builds
          DOCKERFILES_MATRIX="[]"
          if [ -n "$DOCKERFILES_CHANGED" ]; then
            DOCKERFILES_TRIMMED=$(echo "$DOCKERFILES_CHANGED" | xargs)
            if [ -n "$DOCKERFILES_TRIMMED" ]; then
              DOCKERFILES_MATRIX=$(jq -n -c --arg files "$DOCKERFILES_TRIMMED" '$files | split(" ") | map(select(length > 0))')
              if ! echo "$DOCKERFILES_MATRIX" | jq . >/dev/null 2>&1; then
                echo "Error: Invalid JSON generated for matrix"
                exit 1
              fi
            fi
          fi
          
          # Set outputs
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          printf "dockerfiles_matrix=%s\n" "$DOCKERFILES_MATRIX" >> $GITHUB_OUTPUT
          printf "ansible_is_changed=%s\n" "$ANSIBLE_IS_CHANGED" >> $GITHUB_OUTPUT
          
          # Summary
          echo "Changed files: $CHANGED_FILES"
          echo "Dockerfiles matrix: $DOCKERFILES_MATRIX"
          echo "Ansible changed: $ANSIBLE_IS_CHANGED"
  
  build:
    needs: [detect-changes]
    if: | 
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      (needs.detect-changes.result == 'success' && needs.detect-changes.outputs.dockerfiles_matrix != '[]') || 
      (needs.detect-changes.result == 'skipped' && github.event_name == 'workflow_dispatch' && inputs.build)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.detect-changes.outputs.dockerfiles_matrix || '["Dockerfile.prod", "Dockerfile.prod.test", "Dockerfile.prod.format-lint"]') }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.dockerfile }}
        uses: ./.github/actions/build-image
        with:
          image-name: ${{ matrix.dockerfile == 'Dockerfile.prod' && 'ansible-prod' || matrix.dockerfile == 'Dockerfile.prod.test' && 'ansible-prod-test' || matrix.dockerfile == 'Dockerfile.prod.format-lint' && 'ansible-prod-format-lint' }}
          dockerfile-path: ./${{ matrix.dockerfile }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  format-lint:
    needs: [detect-changes, build]
    if: |
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      (needs.build.result == 'success' || needs.build.result == 'skipped') &&
      (inputs.format-lint ||
      (needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.ansible_is_changed == 'true') ||
      (needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.dockerfiles_matrix != '' && contains(fromJson(needs.detect-changes.outputs.dockerfiles_matrix), 'Dockerfile.prod.format-lint')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run formatting and linting
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-format-lint:latest bash .github/scripts/ansible-prod-format-lint.sh

      - name: Commit formatting changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Auto-format YAML files with Prettier"
            git push
          else
            echo "No formatting changes to commit"
          fi

  test:
    needs: [detect-changes, build, format-lint]
    if: |
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      (needs.build.result == 'success' || needs.build.result == 'skipped') &&
      (needs.format-lint.result == 'success' || needs.format-lint.result == 'skipped') &&
      (inputs.test ||
      (needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.ansible_is_changed == 'true') ||
      (needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.dockerfiles_matrix != '' && contains(fromJson(needs.detect-changes.outputs.dockerfiles_matrix), 'Dockerfile.prod.test')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-test:latest bash .github/scripts/ansible-prod-test.sh
