name: Main Production Pipeline

on:
  push:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile*'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile*'
  workflow_dispatch:
    inputs:
      build:
        description: 'Build Docker images'
        required: false
        default: false
        type: boolean
      format-lint:
        description: 'Format and lint Ansible code'
        required: false
        default: true
        type: boolean
      test:
        description: 'Test Ansible code'
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  packages: write

jobs:
  detect-changes:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.detect.outputs.changed_files }}
      dockerfiles-matrix: ${{ steps.detect.outputs.dockerfiles-matrix }}
      ansible-is-changed: ${{ steps.detect.outputs.ansible-is-changed }}
      security-scan-needed: ${{ steps.detect.outputs.security_scan_needed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: detect
        run: |
          # Configuration
          DOCKERFILE_PATTERNS=("Dockerfile.prod" "Dockerfile.prod.test" "Dockerfile.prod.format-lint" "Dockerfile.prod.security-scan")
          ANSIBLE_PATTERN="ansible/"
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            CHANGED_FILES="ansible/**/* Dockerfile*"
          else
            # Get changed files with error handling
            if [ -z "${{ github.event.before }}" ] || [ -z "${{ github.sha }}" ]; then
              echo "Warning: Missing commit references, using empty diff"
              CHANGED_FILES=""
            else
              CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 2>/dev/null || echo "")
            fi
          fi
          
          echo "All changed files: $CHANGED_FILES"
          
          # Detect Dockerfile changes
          DOCKERFILES_CHANGED=""
          
          for pattern in "${DOCKERFILE_PATTERNS[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "^${pattern}$"; then
              echo "Found ${pattern} changes"
              DOCKERFILES_CHANGED="${DOCKERFILES_CHANGED:+$DOCKERFILES_CHANGED }$pattern"
            fi
          done
          
          # Detect Ansible changes
          ANSIBLE_IS_CHANGED="false"
          if echo "$CHANGED_FILES" | grep -q "$ANSIBLE_PATTERN"; then
            ANSIBLE_IS_CHANGED="true"
          fi
          
          # Build matrix for Docker builds
          DOCKERFILES_MATRIX="[]"
          if [ -n "$DOCKERFILES_CHANGED" ]; then
            # Remove leading/trailing whitespace and ensure we have content
            DOCKERFILES_TRIMMED=$(echo "$DOCKERFILES_CHANGED" | xargs)
            if [ -n "$DOCKERFILES_TRIMMED" ]; then
              # Create JSON array more reliably using jq directly with compact output
              DOCKERFILES_MATRIX=$(jq -n -c --arg files "$DOCKERFILES_TRIMMED" '$files | split(" ") | map(select(length > 0))')
              # Validate JSON format
              if ! echo "$DOCKERFILES_MATRIX" | jq . >/dev/null 2>&1; then
                echo "Error: Invalid JSON generated for matrix"
                exit 1
              fi
            fi
          fi
          
          # Determine if security scan is needed
          SECURITY_SCAN_NEEDED="false"
          if [ -n "$CHANGED_FILES" ]; then
            SECURITY_SCAN_NEEDED="true"
          fi
          
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          printf "dockerfiles-matrix=%s\n" "$DOCKERFILES_MATRIX" >> $GITHUB_OUTPUT
          printf "ansible-is-changed=%s\n" "$ANSIBLE_IS_CHANGED" >> $GITHUB_OUTPUT
          printf "security_scan_needed=%s\n" "$SECURITY_SCAN_NEEDED" >> $GITHUB_OUTPUT
          
          echo "Changed files: $CHANGED_FILES"
          echo "Dockerfiles changed: $DOCKERFILES_CHANGED"
          echo "Ansible is changed: $ANSIBLE_IS_CHANGED"
          echo "Security scan needed: $SECURITY_SCAN_NEEDED"

  build:
    needs: [detect-changes]
    if: | 
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      ((needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.dockerfiles-matrix != '[]') || 
      inputs.build)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.detect-changes.outputs.dockerfiles-matrix || '["Dockerfile.prod", "Dockerfile.prod.test", "Dockerfile.prod.format-lint"]') }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.dockerfile }}
        uses: ./.github/actions/build-image
        with:
          image-name: ${{ matrix.dockerfile == 'Dockerfile.prod' && 'ansible-prod' || matrix.dockerfile == 'Dockerfile.prod.test' && 'ansible-prod-test' || matrix.dockerfile == 'Dockerfile.prod.format-lint' && 'ansible-prod-format-lint' || 'ansible-prod-security-scan' }}
          dockerfile-path: ./${{ matrix.dockerfile }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  security-scan-fast:
    needs: [detect-changes, build]
    if: |
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      (needs.build.result == 'success' || needs.build.result == 'skipped') &&
      needs.detect-changes.outputs.security-scan-needed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Only current commit for fast scan

      - name: Run Fast Security Scan
        uses: ./.github/actions/security-scan
        with:
          scan-type: 'fast'
          target-files: ${{ needs.detect-changes.outputs.changed-files }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  format-lint:
    needs: [detect-changes, build, security-scan-fast]
    if: |
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      (needs.security-scan-fast.result == 'success' || needs.security-scan-fast.result == 'skipped') &&
      (needs.build.result == 'success' || needs.build.result == 'skipped') &&
      (inputs.format-lint ||
      (needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.ansible-is-changed == 'true') ||
      (needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.dockerfiles-matrix != '' && contains(fromJson(needs.detect-changes.outputs.dockerfiles-matrix), 'Dockerfile.prod.format-lint')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Try to pull custom format-lint image
        id: pull-image
        uses: ./.github/actions/pull-image
        with:
          image-name: ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-format-lint:latest
          output-name: custom-image-available

      - name: Run formatting and linting (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-format-lint:latest bash .github/scripts/ansible-prod-format-lint.sh

      - name: Run formatting and linting (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace python:3.13-slim bash -c "
            apt-get update && apt-get install -y nodejs npm
            npm install -g prettier
            pip install --no-cache-dir ansible ansible-lint
            bash .github/scripts/ansible-prod-format-lint.sh
          "

      - name: Commit formatting changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Auto-format YAML files with Prettier"
            git push
          else
            echo "No formatting changes to commit"
          fi
  
  test:
    needs: [detect-changes, build, security-scan-fast, format-lint]
    if: |
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      (needs.security-scan-fast.result == 'success' || needs.security-scan-fast.result == 'skipped') &&
      (needs.build.result == 'success' || needs.build.result == 'skipped') &&
      (needs.format-lint.result == 'success' || needs.format-lint.result == 'skipped') &&
      (inputs.test ||
      (needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.ansible-is-changed == 'true') ||
      (needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.dockerfiles-matrix != '' && contains(fromJson(needs.detect-changes.outputs.dockerfiles-matrix), 'Dockerfile.prod.test')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Try to pull custom test image
        id: pull-image
        uses: ./.github/actions/pull-image
        with:
          image-name: ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-test:latest
          output-name: custom-image-available

      - name: Run tests (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-test:latest bash .github/scripts/ansible-prod-test.sh

      - name: Run tests (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace python:3.13-slim bash -c "
            pip install --no-cache-dir ansible ansible-prod-test
            bash .github/scripts/ansible-prod-test.sh
          " 
