name: Deploy Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'ansible/**/*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    if: ${{ secrets.AUTO_DEPLOY == 'true' }}
    uses: ./.github/workflows/reusable-ansible-base.yml
    with:
      playbook-path: ansible/playbooks/deploy.yml