name: Example Infrastructure Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**/*'
      - '.github/workflows/example-infrastructure.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ansible/**/*'
      - '.github/workflows/example-infrastructure.yml'
  workflow_dispatch:
    inputs:
      auto_bootstrap:
        description: 'Auto bootstrap infrastructure'
        required: false
        default: false
        type: boolean
      auto_deploy:
        description: 'Auto deploy application'
        required: false
        default: false
        type: boolean

jobs:
  # Bootstrap stage - sets up initial environment
  bootstrap:
    uses: ./.github/workflows/reusable-bootstrap.yml
    with:
      auto_bootstrap: ${{ github.event_name == 'workflow_dispatch' && inputs.auto_bootstrap || github.ref == 'refs/heads/main' }}
      ansible-user: ${{ secrets.ANSIBLE_USER || 'ubuntu' }}
    secrets:
      ANSIBLE_HOSTS: ${{ secrets.ANSIBLE_HOSTS }}
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

  # Deploy stage - deploys the application
  deploy:
    needs: bootstrap
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      auto_deploy: ${{ github.event_name == 'workflow_dispatch' && inputs.auto_deploy || github.ref == 'refs/heads/main' }}
      ansible-user: ${{ secrets.ANSIBLE_USER || 'ubuntu' }}
    secrets:
      ANSIBLE_HOSTS: ${{ secrets.ANSIBLE_HOSTS }}
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }} 