name: Lint Ansible Code

on:
  push:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile.lint'
  pull_request:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile.lint'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || contains(github.event.workflow_run.head_commit.message, 'Dockerfile.lint')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Try to pull custom lint image
        id: pull-image
        run: |
          if docker pull ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-lint:latest; then
            echo "custom-image-available=true" >> $GITHUB_OUTPUT
            echo "Successfully pulled custom lint image"
          else
            echo "custom-image-available=false" >> $GITHUB_OUTPUT
            echo "Failed to pull custom lint image, will use fallback"
          fi

      - name: Format YAML files with Prettier (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-lint:latest bash -c "
            echo 'Formatting YAML files with Prettier...'
            prettier --write 'ansible/**/*.yml' || true
            echo 'Prettier formatting completed'
          "

      - name: Format YAML files with Prettier (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace python:3.13-slim bash -c "
            apt-get update && apt-get install -y nodejs npm
            npm install -g prettier
            echo 'Formatting YAML files with Prettier...'
            prettier --write 'ansible/**/*.yml' || true
            echo 'Prettier formatting completed'
          "

      - name: Run yamllint (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-lint:latest bash -c "
            echo 'Running yamllint...'
            yamllint ansible/ || exit 1
            echo 'yamllint completed successfully'
          "

      - name: Run yamllint (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace python:3.13-slim bash -c "
            pip install --no-cache-dir yamllint
            echo 'Running yamllint...'
            yamllint ansible/ || exit 1
            echo 'yamllint completed successfully'
          "

      - name: Run ansible-lint (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-lint:latest bash -c "
            echo 'Installing required ansible collections...'
            ansible-galaxy collection install -r ansible/collections/requirements.yml
            echo 'Running ansible-lint on roles...'
            for role in ansible/roles/*/; do
              echo \"CHECKING ROLE: \$role\"
              ansible-lint \"\$role\" --nocolor || exit 1
            done
            echo 'Running ansible-lint on playbooks...'
            for playbook in ansible/playbooks/*.yml; do
              echo \"CHECKING PLAYBOOK: \$playbook\"
              ansible-lint \"\$playbook\" --nocolor || exit 1
            done
            echo 'ansible-lint completed successfully'
          "

      - name: Run ansible-lint (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace python:3.13-slim bash -c "
            pip install --no-cache-dir ansible ansible-lint
            echo 'Installing required ansible collections...'
            ansible-galaxy collection install -r ansible/collections/requirements.yml
            echo 'Running ansible-lint on roles...'
            for role in ansible/roles/*/; do
              echo \"CHECKING ROLE: \$role\"
              ansible-lint \"\$role\" --nocolor || exit 1
            done
            echo 'Running ansible-lint on playbooks...'
            for playbook in ansible/playbooks/*.yml; do
              echo \"CHECKING PLAYBOOK: \$playbook\"
              ansible-lint \"\$playbook\" --nocolor || exit 1
            done
            echo 'ansible-lint completed successfully'
          " 