name: Main CI/CD Pipeline

on:
  push:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile*'
  pull_request:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile*'
  workflow_dispatch:
    inputs:
      build:
        description: 'Build Docker images'
        required: false
        default: false
        type: boolean
      lint:
        description: 'Lint Ansible code'
        required: false
        default: true
        type: boolean
      test:
        description: 'Test Ansible code'
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      dockerfiles-changed: ${{ steps.detect.outputs.dockerfiles }}
      ansible-changed: ${{ steps.detect.outputs.ansible }}
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changes
        id: detect
        run: |
          # Configuration
          DOCKERFILE_PATTERNS=("Dockerfile.prod" "Dockerfile.prod.test" "Dockerfile.prod.lint")
          ANSIBLE_PATTERN="ansible/"
          
          # Get changed files with error handling
          if [ -z "${{ github.event.before }}" ] || [ -z "${{ github.sha }}" ]; then
            echo "Warning: Missing commit references, using empty diff"
            CHANGED_FILES=""
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 2>/dev/null || echo "")
          fi
          
          echo "All changed files: $CHANGED_FILES"
          
          # Detect Dockerfile changes
          DOCKERFILES=""
          
          for pattern in "${DOCKERFILE_PATTERNS[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "^${pattern}$"; then
              echo "Found ${pattern} changes"
              DOCKERFILES="${DOCKERFILES:+$DOCKERFILES }$pattern"
            fi
          done
          
          # Detect Ansible changes
          ANSIBLE_CHANGED="false"
          if echo "$CHANGED_FILES" | grep -q "$ANSIBLE_PATTERN"; then
            ANSIBLE_CHANGED="true"
          fi
          
          # Build matrix for Docker builds
          MATRIX="[]"
          if [ -n "$DOCKERFILES" ]; then
            # Remove leading/trailing whitespace and ensure we have content
            DOCKERFILES_TRIMMED=$(echo "$DOCKERFILES" | xargs)
            if [ -n "$DOCKERFILES_TRIMMED" ]; then
              # Create JSON array more reliably using jq directly with compact output
              MATRIX=$(jq -n -c --arg files "$DOCKERFILES_TRIMMED" '$files | split(" ") | map(select(length > 0))')
              # Validate JSON format
              if ! echo "$MATRIX" | jq . >/dev/null 2>&1; then
                echo "Error: Invalid JSON generated for matrix"
                exit 1
              fi
            fi
          fi
          
          printf "dockerfiles=%s\n" "$DOCKERFILES" >> $GITHUB_OUTPUT
          printf "ansible=%s\n" "$ANSIBLE_CHANGED" >> $GITHUB_OUTPUT
          printf "matrix=%s\n" "$MATRIX" >> $GITHUB_OUTPUT
          
          echo "Dockerfiles changed: $DOCKERFILES"
          echo "Ansible changed: $ANSIBLE_CHANGED"
          echo "Matrix JSON: $MATRIX"
  
  build:
    needs: detect-changes
    if: | 
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      ((needs.detect-changes.result != 'skipped' && needs.detect-changes.outputs.matrix != '[]') || 
      inputs.build)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.dockerfile }}
        uses: ./.github/actions/build-image
        with:
          image-name: ${{ matrix.dockerfile == 'Dockerfile.prod' && 'ansible-prod' || matrix.dockerfile == 'Dockerfile.prod.test' && 'ansible-prod-test' || 'ansible-prod-lint' }}
          dockerfile-path: ./${{ matrix.dockerfile }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  lint:
    needs: [detect-changes, build]
    if: |
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      (needs.build.result == 'success' || needs.build.result == 'skipped') &&
      (inputs.lint ||
      needs.detect-changes.outputs.ansible-changed == 'true' ||
      contains(needs.detect-changes.outputs.dockerfiles-changed, 'Dockerfile.prod.lint'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Try to pull custom lint image
        id: pull-image
        run: |
          if docker pull ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-lint:latest; then
            echo "custom-image-available=true" >> $GITHUB_OUTPUT
          else
            echo "custom-image-available=false" >> $GITHUB_OUTPUT
          fi

      - name: Run linting (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-lint:latest bash .github/scripts/ansible-prod-lint.sh

      - name: Run linting (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace python:3.13-slim bash -c "
            pip install --no-cache-dir yamllint ansible ansible-prod-lint
            bash .github/scripts/ansible-prod-lint.sh
          "
  
  test:
    needs: [detect-changes, build, lint]
    if: |
      always() &&
      (needs.detect-changes.result == 'success' || needs.detect-changes.result == 'skipped') &&
      (needs.build.result == 'success' || needs.build.result == 'skipped') &&
      (needs.lint.result == 'success' || needs.lint.result == 'skipped') &&
      (inputs.test ||
      needs.detect-changes.outputs.ansible-changed == 'true' ||
      contains(needs.detect-changes.outputs.dockerfiles-changed, 'Dockerfile.prod.test'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Try to pull custom test image
        id: pull-image
        run: |
          if docker pull ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-test:latest; then
            echo "custom-image-available=true" >> $GITHUB_OUTPUT
          else
            echo "custom-image-available=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-test:latest bash .github/scripts/ansible-prod-test.sh

      - name: Run tests (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace python:3.13-slim bash -c "
            pip install --no-cache-dir ansible ansible-prod-test
            bash .github/scripts/ansible-prod-test.sh
          " 