name: Manual Full Security Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trufflehog-comprehensive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Comprehensive Security Scan
        uses: ./.github/actions/security-scan
        with:
          scan-type: 'comprehensive'
          scan-commits: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}