name: Manual Lint and Test Pipeline

on:
  workflow_dispatch:
    inputs:
      lint:
        description: 'Run lint'
        required: false
        default: true
        type: boolean
      test:
        description: 'Run tests'
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  packages: read

jobs:
  lint:
    if: inputs.lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linting
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-lint:latest \
            bash .github/scripts/ansible-prod-lint.sh

  test:
    if: inputs.test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod-test:latest \
            bash .github/scripts/ansible-prod-test.sh
