name: Deploy Infrastructure

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    if: ${{ env.AUTO_DEPLOY == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        uses: ./.github/workflows/reusable-ansible-base.yml
        with:
          playbook-path: ansible/playbooks/deploy.yml