name: Reusable Ansible Base

on:
  workflow_call:
    inputs:
      playbook-path:
        description: 'Path to the Ansible playbook to run'
        required: true
        type: string
      inventory-hosts:
        description: 'Comma-separated list of hosts for inventory'
        required: true
        type: string
      ansible-user:
        description: 'Ansible user for SSH connections'
        required: true
        type: string
        default: 'ubuntu'
      ssh-private-key:
        description: 'SSH private key for server access'
        required: true
        type: string
      ssh-known-hosts:
        description: 'SSH known hosts content'
        required: false
        type: string
        default: ''

env:
  ANSIBLE_HOSTS: ${{ inputs.inventory-hosts }}
  ANSIBLE_USER: ${{ inputs.ansible-user }}

jobs:
  ansible-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          if [ -n "${{ inputs.ssh-known-hosts }}" ]; then
            echo "${{ inputs.ssh-known-hosts }}" > ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
          else
            # Add common hosts to known_hosts to avoid prompts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts 2>/dev/null || true
          fi

      - name: Generate Inventory
        run: |
          cd ansible
          ansible-playbook playbooks/generate_inventory.yml

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini ${{ inputs.playbook-path }} --verbose 