name: Reusable Deploy Infrastructure

on:
  workflow_call:
    inputs:
      auto_deploy:
        description: 'Whether to auto deploy'
        required: true
        default: false
        type: boolean
    secrets:
      ANSIBLE_HOSTS:
        required: true
      ANSIBLE_USER:
        required: false
      SSH_PRIVATE_KEY:
        required: true
      SSH_KNOWN_HOSTS:
        required: false

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    if: ${{ inputs.auto_deploy == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout templates repo for local actions
        uses: actions/checkout@v4
        with:
          repository: SkiesGames/SkiesDota-CI-CD-Templates
          path: templates

      - name: Setup Docker
        uses: ./templates/.github/actions/setup-docker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Try to pull custom Ansible image
        id: pull-image
        uses: ./templates/.github/actions/pull-image
        with:
          image-name: ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod:latest
          output-name: custom-image-available

      - name: Generate Inventory (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        env:
          ANSIBLE_HOSTS: ${{ secrets.ANSIBLE_HOSTS }}
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e ANSIBLE_HOSTS \
            -e ANSIBLE_USER \
            ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod:latest \
            bash -c "
              cd ansible && 
              ansible-playbook playbooks/generate_inventory.yml
            "

      - name: Run Deploy Playbook (Custom Image)
        if: steps.pull-image.outputs.custom-image-available == 'true'
        env:
          ANSIBLE_HOSTS: ${{ secrets.ANSIBLE_HOSTS }}
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e ANSIBLE_HOSTS \
            -e ANSIBLE_USER \
            -e SSH_PRIVATE_KEY \
            -e SSH_KNOWN_HOSTS \
            ghcr.io/skiesgames/skiesdota-ci-cd-templates/ansible-prod:latest \
            bash -c "
              ansible-playbook ansible/playbooks/setup_ci_env.yml
              cd ansible && 
              ansible-playbook -i inventory.ini playbooks/deploy.yml --verbose
            "

      - name: Generate Inventory (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        env:
          ANSIBLE_HOSTS: ${{ secrets.ANSIBLE_HOSTS }}
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e ANSIBLE_HOSTS \
            -e ANSIBLE_USER \
            python:3.13-slim \
            bash -c "
              apt-get update && apt-get install -y openssh-client
              pip install --no-cache-dir ansible
              cd ansible && 
              ansible-playbook playbooks/generate_inventory.yml
            "

      - name: Run Deploy Playbook (Fallback)
        if: steps.pull-image.outputs.custom-image-available == 'false'
        env:
          ANSIBLE_HOSTS: ${{ secrets.ANSIBLE_HOSTS }}
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e ANSIBLE_HOSTS \
            -e ANSIBLE_USER \
            -e SSH_PRIVATE_KEY \
            -e SSH_KNOWN_HOSTS \
            python:3.13-slim \
            bash -c "
              apt-get update && apt-get install -y openssh-client
              pip install --no-cache-dir ansible
              ansible-playbook ansible/playbooks/setup_ci_env.yml
              cd ansible && 
              ansible-playbook -i inventory.ini playbooks/deploy.yml --verbose
            "`