name: Test Ansible Code

on:
  push:
    paths:
      - 'ansible/**/*'
      - 'Dockerfile.test'
  pull_request:
    paths:
      - 'ansible/**/*'
  workflow_dispatch:

permissions:
  actions: read

jobs:
  test-ansible:
    uses: ./.github/workflows/reusable-test-ansible.yml
    with:
      wait-for-build: true
      build-workflow-name: 'Build Docker Images' 