name: Test Reusable Workflow

on:
  workflow_call:
    inputs:
      test-input:
        description: 'Test input'
        required: false
        type: string
        default: 'hello'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Test input: ${{ inputs.test-input }}"
